name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@main
      with:
        go-version: 1.19
    - uses: actions/checkout@main
    - name: Test
      run: go test -v -cover .
